### PR TITLE
Tart-39

### PR DESCRIPTION
**Pull request by adamponiatowski**
updated ending cutscene

### CODE REVIEW

**Comment by FierceLlama** [comment]
@adamponiatowski I tried to see the new end game matinee, but it isn't working for Thomas or me.  The particle effect goes off into the air, and then it returns to the start screen, no movie plays, even thought the play matinee event fires off.  Also, the start screen is missing the particle effects Thomas put in, so we may need to take a look at what's going on between your branch and the other shit in master, as well as the end game matinee.

**Comment by tmoss343** [comment]
@adamponiatowski I had the same experience as @FierceLlama on my machine

**Comment by adamponiatowski** [comment]
@FierceLlama @tmoss343 im not sure what the issue is since the cutscene works fine for me. can you check if the cutscene level works by itself? As for the particle effect it seems like it is no longer set for some reason. I had to go and reset it in the start screen level

**Comment by tmoss343** [comment]
@adamponiatowski When I start that level it just cuts to black and goes to the start screen. Could it be that we don't have the file like that issue you were saying earlier for the media player?

**Comment by adamponiatowski** [comment]
ahhhh ok so 2 things could be wrong. Check the media player asset itself and if that opens and plays then you should have the file, if not then that is where the issue is although I did add the .wmv file into the project so maybe it just needs to be re-linked by editing the file source in the details panel so that it points to the file in our content folder. The second issue could be in the level blueprint of the cutscene level. In the blueprint check if the variable "media player ref" is actually assigned to the correct media player in the details panel. If none of those work then I don't know where the issue would be since it is not happening on my end.

**Comment by tmoss343** [comment]
@adamponiatowski it did just need to be relinked for me I pushed a change so if you can make sure that works I approve this.

**Comment by adamponiatowski** [comment]
I figured that was the most likely culprit of the stupid media player. I won't be able to check until around 9 however since I am at work right now.

**Comment by adamponiatowski** [comment]
alright everything is working smooth for this on my side! if anyone wants to check again on another machine, I can wait to merge it.

**Comment by tmoss343** [comment]
Alright this is looking good to me @adamponiatowski

**Pull request merged**
